title: Marina
description: My Personal Blog
author: Marina
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/Marina-Ma/Marina-Ma.github.io
about: learn to learn

baseurl: "https://github.com/Marina-Ma/Marina-Ma.github.io"
url: "https://github.com/Marina-Ma/Marina-Ma.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
